### ISSUE TITLE
Recent update

### ISSUE THREAD

**Issue by yinyanghu** [yinyanghu/CLRS-Solutions#1]
Hello everyone!

It's a long time since I updated my solutions last time.

I'm currently exchanging in the **University of Waterloo**, Canada. And I have a course about algorithm _CS 466: Design and Analysis of Algorithms_ this term. I'm so interested in algorithm design and analysis that I want read the textbook **CLRS** again as well as fix the error in my solution, translate to English and add new chapters solution(**Goal: covering all the chapter of CLRS**).

Also, I have read some other algorithm or theoretical textbooks and I will try my best to share my solution for the problems in these books.
- [Algorithms](http://www.amazon.ca/Algorithms-Sanjoy-Dasgupta/dp/0073523402) _Sanjoy Dasgupta, Christos Papadimitriou and Umesh Vazirani_
- [Probability and Computing: Randomized Algorithms and Probabilistic Analysis](http://www.amazon.ca/Probability-Computing-Randomized-Algorithms-Probabilistic/dp/0521835402) _Michael Mitzenmacher and Eli Upfal_
- [Introduction to Automata Theory, Languages, and Computation](http://www.amazon.ca/Introduction-Automata-Theory-Languages-Computation/dp/0321455363) _John E. Hopcroft, Rajeev Motwani and Jeffrey D. Ullman_

**Maybe this work will last for 1 years, since I will apply Master/PhD program for the future study and complete a final project(a Starcraft AI using BWAPI) for my Bachelor's Degree in the future several months.**

If you want to join me or discuss some problems with me, feel free to email me or connect me on Github. Hope for more and more participants.

Thank you.

Regards,
[Jian Li](http://yinyanghu.github.io)
lijianxp2005@gmail.com

**Comment by yoseif14** [comment]
AT10 -A
Android 4.2.1
