### ISSUE TITLE
Many solutions are in Chinese

### ISSUE THREAD

**Issue by mahiuchun** [yinyanghu/CLRS-Solutions#2]
This is not a problem by itself. You can use whatever language you like. 
(而且我能看懂中文。)

The problem is that somehow your CLRS-Solutions become number 1 in Google search  for keyword "clrs solutions". And your README are all in English. People would expect your solution being written entirely in English also.

I guess you can add some Chinese to your README. So no matter the viewer understand Chinese or not, he/she would have a right expectation.

**Comment by yinyanghu** [comment]
Exactly! I have received lots of email for hoping me to translate the Chinese part of solution into English.
Just as I said in the README, I am about to rewrite my solution as well as add some new materials.
But I am really busy these days. @_@
If you want to join me, or contribute to this repository, feel free to tell me.
Anyway, thank you for your suggestion.
