### ISSUE TITLE
Problem 2.4 (Inversions) - Is "counted" variable necessary?

### ISSUE THREAD

**Issue by Hydronicx** [yinyanghu/CLRS-Solutions#6]
Hey. In problem 2.4 dealing with inversions, is the "counted" boolean variable necessary in the modified merge sort algorithm? It seems to me that there will never be a case where "counted == TRUE and L[i] > R[j]", because every time "counted" is set to TRUE (after adding something to the "inversions" variable), we are **guaranteed** that in the same pass of the outer for loop, "counted" is going to be set to FALSE again in the "else" clause.

The "counted" variable is used in the official solution manual too. Did the authors fail to notice this, or is there some other reason why "counted" is necessary?

**Comment by yinyanghu** [comment]
Hey. I think "counted" boolean variable is necessary, because otherwise you would count more inversions. If you think this doesn't make sense, you could run this algorithm (pseudo-code) on the paper, step by step with a small test input, say 10 elements. I think this could help you a lot.

**Comment by Hydronicx** [comment]
I did try it step by step on paper, and even implemented it without the "counted" variable, and it gave correct results. I still can't see how it's necessary. I think you can prove that you will never enter the loop with "counted == TRUE" (from what I said above)...

**Comment by yinyanghu** [comment]
I just double checked on paper. Yes, I think you are correct and the "counted" variable is not necessary.
Thanks for pointing out this.
